### ISSUE TITLE
Standardize terminology

### ISSUE THREAD

**Issue by rhc54** [openpmix/mpir-to-pmix-guide#3]
In the Standard, we talk about "direct" and "indirect" launch cases. The terms used here are "proxy" and "non-proxy" - but both seem to be referring to the "indirect" launch case. The present interesting use-cases, so perhaps there is justification in keeping both of them. However, it would be nice if at least the documentation made it clear that these are "indirect" cases, and if support was added for the "direct" case.

**Comment by jjhursey** [comment]
We picked up the proxy/non-proxy wording from the C++ version. I agree about clarifying the documentation. I'll work on that.
